import sys
import os
from crescent.Crescent import Crescent

USAGE = '''\
USAGE:
{name} COMMAND

COMMANDS:
update  - Run clean, write and call update-desktop-database (in order)
clean   - Remove any .desktop which would not be generated by Crescent
write   - Generate Desktop Entries and write them to files
path    - Write Crescent\'s Directory Entries folder path to stdout
config  - Write Crescent\'s config folder path to stdout
'''.format(name=os.path.basename(sys.argv[0]))

crescent = Crescent()

def get_path():
    print(crescent.get_apps_dir())

def get_config():
    print(crescent.get_config_dir())

if __name__ == '__main__':
    commands = {
        'update': crescent.update,
        'write': crescent.write_entries,
        'clean': crescent.remove_leftovers,
        'path': get_path,
        'config': get_config,
    }
    if len(sys.argv) is not 2 or sys.argv[1] not in commands:
        print(USAGE, file=sys.stderr)
        sys.exit(1)
    commands[sys.argv[1]]()
