import sys
from crescent.Crescent import Crescent

USAGE = '''\
USAGE:
{name} COMMAND

COMMANDS:
update  - Run clean, write and call update-desktop-database (in order)
clean   - Remove any .desktop which would not be generated by Crescent
write   - Generate Desktop Entries and write them to files
path    - Write Crescent\'s Directory Entries folder path to stdout
'''.format(name=sys.argv[0])

if __name__ == '__main__':
    crescent = Crescent()
    commands = {
        'update': crescent.update,
        'write': crescent.write_entries,
        'clean': crescent.remove_leftovers,
        'path': crescent.get_apps_dir,
    }
    if len(sys.argv) is not 2 or sys.argv[1] not in commands:
        print(USAGE, file=sys.stderr)
        sys.exit(1)
    commands[sys.argv[1]]()
